# Generated by Django 5.2.1 on 2025-05-25 09:27

import django.core.validators
import django.db.models.deletion
import patients_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identification_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')])),
                ('date_of_birth', models.DateField(validators=[patients_app.models.validate_date_of_birth])),
                ('insurance_provider', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(validators=[patients_app.models.validate_appointment_time])),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='scheduled', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients_app.patient')),
            ],
        ),
    ]
