# Generated by Django 5.2.1 on 2025-05-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='identification_number_number',
            new_name='identification_number',
        ),
    ]
